/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { getKorpa } from '@/lib/actions/korpa';
import type { ReactNode } from 'react';
import AuthProvider from "./components/AuthProvider";
import { cookies } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Client Prodavnica",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
    children: ReactNode;
}): Promise<React.ReactElement> {
  const session = await getServerSession(authOptions);
  const isLoggedIn = !!session?.user;

  const cookieStore = await cookies();
  const lang = cookieStore.get('lang')?.value || 'sr';

  let brojUKorpi = 0;
  if (isLoggedIn && session?.user?.id) {
    try {
      const korpa = await getKorpa(session.user.id);
      if (korpa.success && korpa.data?.stavke) {
        brojUKorpi = korpa.data.stavke.reduce((sum, s) => sum + (s.kolicina || 1), 0);
      }
    } catch (e) {
      brojUKorpi = 0;
    }
  }

  return (
    <html lang={lang}>
      <head>
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
